global:
  reporters:
    jmx: true
    csv:
      dir: metrics
      period: 30
    slf4j:
      logger: org.apache.sling.metrics.status
      period: 30
org.apache.jackrabbit.oak.jcr.repository.RepositoryImpl:
  loginx : timer
  createSessionDelegate: timer
  createSessionContext: timer
  createListeningScheduledExecutorService: timer
  getRefreshInterval: timer
org.apache.jackrabbit.oak.jcr.delegate.SessionDelegate:
  refreshAtNextAccess: timer
  commit: timer
  save: timer
  refresh: timer
  move: timer
   
